name: CI

on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
            - run: pnpm install
            - run: npm run lint
            - run: npm run build
            - run: npm run test:ci
            - run: npm run cy:test
            - name: Upload Cypress screenshots
              uses: actions/upload-artifact@v4
              if: ${{ failure() }}
              with:
                  name: cypress_screenshots
                  path: cypress/screenshots
